import { validateRequest } from '@/lib/auth';
import { SessionProvider } from '@/lib/auth/context';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';
import Header from './header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider value={session}>
          <div className="flex flex-col min-h-screen">
            <Header />
            <div className="flex flex-1">
              <aside className="hidden p-4 space-y-4 w-64 border-r lg:block">
                <nav className="space-y-2">
                  <Link
                    href="/"
                    className="block py-2 px-4 rounded-md hover:bg-accent"
                  >
                    Home
                  </Link>
                  <Link
                    href="/about"
                    className="block py-2 px-4 rounded-md hover:bg-accent"
                  >
                    About
                  </Link>
                  <Link
                    href="/contact"
                    className="block py-2 px-4 rounded-md hover:bg-accent"
                  >
                    Contact
                  </Link>
                </nav>
              </aside>
              <main className="flex-1 p-4">{children}</main>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
